### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [asingh1969/tc359-project9#1]
This is looking good apart from the indentation. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs. (I see some [hard-tabs here](https://github.com/asingh1969/tc359-project9/blob/master/app/helpers/static_helper.rb) and [four-space tabs here](https://github.com/asingh1969/tc359-project9/blob/master/app/assets/stylesheets/application.css), for example.)

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by asingh1969** [comment]
Edited the indentation.

**Comment by chrisvfritz** [comment]
The hard-tabs look much better, but I still see [four-space tabs here](https://github.com/asingh1969/tc359-project9/blob/master/app/assets/stylesheets/application.css). Can you fix those to use two spaces instead? I know it's nit-picky, but I want us to get into good habits now, so that when we're dealing with larger files later, it won't be as much work to fix.

**Comment by asingh1969** [comment]
Thanks for the find, it should be good now.

**Comment by chrisvfritz** [comment]
:+1: Looks good.
